//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_AccountAddress
    {
        public int AccountAddress_Id { get; set; }
        public string AccountAddress_Title { get; set; }
        public Nullable<int> AccountAddress_AccountId { get; set; }
        public Nullable<int> AccountAddress_CountryId { get; set; }
        public Nullable<int> AccountAddress_StateId { get; set; }
        public Nullable<int> AccountAddress_CityId { get; set; }
        public Nullable<int> AccountAddress_RegionId { get; set; }
        public Nullable<int> AccountAddress_Address { get; set; }
        public string AccountAddress_ZipCode { get; set; }
        public bool AccountAddress_Default { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
        public virtual RS_Loc_Region RS_Loc_Region { get; set; }
    }
}
