//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_AccountContact
    {
        public int AccountContact_Id { get; set; }
        public int AccountContact_AccountId { get; set; }
        public string AccountContact_Value { get; set; }
        public string AccountContact_Type { get; set; }
        public Nullable<System.DateTime> AccountContact_Date { get; set; }
        public Nullable<bool> AccountContact_Active { get; set; }
        public Nullable<bool> AccountContact_Primary { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
    }
}
