//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Account()
        {
            this.RS_Account1 = new HashSet<RS_Account>();
            this.RS_AccountAddress = new HashSet<RS_AccountAddress>();
            this.RS_AccountContact = new HashSet<RS_AccountContact>();
            this.RS_Request = new HashSet<RS_Request>();
            this.RS_SiteInfo = new HashSet<RS_SiteInfo>();
            this.RS_Transaction = new HashSet<RS_Transaction>();
        }
    
        public int Account_Id { get; set; }
        public Nullable<int> Account_ParentId { get; set; }
        public string Account_Username { get; set; }
        public string Account_Password { get; set; }
        public string Account_DisplayName { get; set; }
        public string Account_Token { get; set; }
        public Nullable<System.DateTime> Account_LastLogin { get; set; }
        public bool Account_Active { get; set; }
        public Nullable<int> Account_RoleId { get; set; }
        public Nullable<int> Account_Commision { get; set; }
        public int Account_LanguageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Account> RS_Account1 { get; set; }
        public virtual RS_Account RS_Account2 { get; set; }
        public virtual RS_Language RS_Language { get; set; }
        public virtual RS_Roles RS_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AccountAddress> RS_AccountAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AccountContact> RS_AccountContact { get; set; }
        public virtual RS_AccountInfo RS_AccountInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Request> RS_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_SiteInfo> RS_SiteInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Transaction> RS_Transaction { get; set; }
    }
}
