//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_AccountInfo
    {
        public int AccountInfo_Id { get; set; }
        public int AccountInfo_AccountId { get; set; }
        public string AccountInfo_FirstName { get; set; }
        public string AccountInfo_LastName { get; set; }
        public string AccountInfo_Gender { get; set; }
        public Nullable<int> AccountInfo_Country_Nationality { get; set; }
        public Nullable<int> AccountInfo_Country_BirthPlace { get; set; }
        public string AccountInfo_PassId { get; set; }
        public string AccountInfo_NationalId { get; set; }
        public string AccountInfo_CompanyName { get; set; }
        public Nullable<System.DateTime> AccountInfo_Birthday { get; set; }
        public string AccountInfo_Picture { get; set; }
        public Nullable<System.DateTime> AccountInfo_RegisterDate { get; set; }
        public Nullable<System.DateTime> AccountInfo_EditDate { get; set; }
        public string AccountInfo_Father { get; set; }
        public string AccountInfo_Mother { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
        public virtual RS_Loc_Country RS_Loc_Country { get; set; }
        public virtual RS_Loc_Country RS_Loc_Country1 { get; set; }
    }
}
