//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Loc_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Loc_City()
        {
            this.RS_Loc_Region = new HashSet<RS_Loc_Region>();
        }
    
        public int City_Id { get; set; }
        public int City_StateId { get; set; }
        public string City_Name { get; set; }
        public Nullable<decimal> City_MapLat { get; set; }
        public Nullable<decimal> City_MapLan { get; set; }
        public Nullable<int> City_WsCode { get; set; }
    
        public virtual RS_Loc_State RS_Loc_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Loc_Region> RS_Loc_Region { get; set; }
    }
}
