//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Language()
        {
            this.RS_Account = new HashSet<RS_Account>();
        }
    
        public int Language_Id { get; set; }
        public string Language_Name { get; set; }
        public string Language_DisplayName { get; set; }
        public string Language_Flag { get; set; }
        public string Language_Iso { get; set; }
        public bool Language_Active { get; set; }
        public string Language_Direction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Account> RS_Account { get; set; }
        public virtual RS_LanguageContent RS_LanguageContent { get; set; }
    }
}
