//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_LanguageContent
    {
        public int LanguageContent_Id { get; set; }
        public string LanguageContent_Group { get; set; }
        public string LanguageContent_TagName { get; set; }
        public string LanguageContent_EN { get; set; }
        public string LanguageContent_TR { get; set; }
        public string LanguageContent_RU { get; set; }
    
        public virtual RS_Language RS_Language { get; set; }
    }
}
