//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Loc_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Loc_State()
        {
            this.RS_Loc_City = new HashSet<RS_Loc_City>();
        }
    
        public int State_Id { get; set; }
        public Nullable<int> State_CountryId { get; set; }
        public string State_Name { get; set; }
        public Nullable<int> State_WsCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Loc_City> RS_Loc_City { get; set; }
        public virtual RS_Loc_Country RS_Loc_Country { get; set; }
    }
}
