//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Request()
        {
            this.RS_Issued = new HashSet<RS_Issued>();
        }
    
        public int Request_Id { get; set; }
        public int Request_SiteId { get; set; }
        public int Request_PackageId { get; set; }
        public System.DateTime Request_StartDate { get; set; }
        public int Request_DurationDay { get; set; }
        public Nullable<int> Request_AccountId { get; set; }
        public int Request_StatusId { get; set; }
        public string Request_TempNo { get; set; }
        public Nullable<System.DateTime> Request_SubmitDate { get; set; }
        public Nullable<int> Request_Weight { get; set; }
        public Nullable<int> Request_Tall { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Issued> RS_Issued { get; set; }
        public virtual RS_Package RS_Package { get; set; }
        public virtual RS_StatusType RS_StatusType { get; set; }
    }
}
