//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_SiteInfo
    {
        public int SiteInfo_Id { get; set; }
        public string SiteInfo_Logo { get; set; }
        public string SiteInfo_LocalName { get; set; }
        public Nullable<int> SiteInfo_AccountId_Admin { get; set; }
        public int SiteInfo_SiteId { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
        public virtual RS_Site RS_Site { get; set; }
    }
}
