//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Site()
        {
            this.RS_SiteInfo = new HashSet<RS_SiteInfo>();
            this.RS_SiteSetting = new HashSet<RS_SiteSetting>();
            this.RS_Transaction = new HashSet<RS_Transaction>();
        }
    
        public int Site_Id { get; set; }
        public string Site_Name { get; set; }
        public string Site_Url { get; set; }
        public string Site_Hosts { get; set; }
        public int Site_LanguageId_Default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_SiteInfo> RS_SiteInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_SiteSetting> RS_SiteSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Transaction> RS_Transaction { get; set; }
    }
}
