//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_SiteSetting
    {
        public int SiteSetting_Id { get; set; }
        public int SiteSetting_SiteId { get; set; }
        public string SiteSetting_Field { get; set; }
        public string SiteSetting_Value { get; set; }
    
        public virtual RS_Site RS_Site { get; set; }
    }
}
