//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Transaction
    {
        public int Transaction_Id { get; set; }
        public int Transaction_SiteId { get; set; }
        public string Transaction_DocumentNo { get; set; }
        public Nullable<int> Transaction_AccountId { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Transaction_Description { get; set; }
        public int Transaction_Type { get; set; }
        public decimal Transaction_Debtor { get; set; }
        public decimal Transaction_Creditor { get; set; }
    
        public virtual RS_Account RS_Account { get; set; }
        public virtual RS_Site RS_Site { get; set; }
        public virtual RS_TransactionType RS_TransactionType { get; set; }
    }
}
