//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_WebService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_WebService()
        {
            this.RS_Package = new HashSet<RS_Package>();
        }
    
        public int WebService_Id { get; set; }
        public Nullable<int> WebService_ProviderId { get; set; }
        public string WebService_Url { get; set; }
        public string WebService_Username { get; set; }
        public string WebService_Password { get; set; }
        public string WebService_ApiToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Package> RS_Package { get; set; }
        public virtual RS_Provider RS_Provider { get; set; }
    }
}
