//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insursys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSEntities : DbContext
    {
        public RSEntities()
            : base("name=RSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RS_Account> RS_Account { get; set; }
        public virtual DbSet<RS_AccountAddress> RS_AccountAddress { get; set; }
        public virtual DbSet<RS_AccountContact> RS_AccountContact { get; set; }
        public virtual DbSet<RS_AccountInfo> RS_AccountInfo { get; set; }
        public virtual DbSet<RS_Issued> RS_Issued { get; set; }
        public virtual DbSet<RS_Language> RS_Language { get; set; }
        public virtual DbSet<RS_LanguageContent> RS_LanguageContent { get; set; }
        public virtual DbSet<RS_Loc_City> RS_Loc_City { get; set; }
        public virtual DbSet<RS_Loc_Country> RS_Loc_Country { get; set; }
        public virtual DbSet<RS_Loc_Region> RS_Loc_Region { get; set; }
        public virtual DbSet<RS_Loc_State> RS_Loc_State { get; set; }
        public virtual DbSet<RS_Menu> RS_Menu { get; set; }
        public virtual DbSet<RS_Package> RS_Package { get; set; }
        public virtual DbSet<RS_Provider> RS_Provider { get; set; }
        public virtual DbSet<RS_Request> RS_Request { get; set; }
        public virtual DbSet<RS_RoleAccess> RS_RoleAccess { get; set; }
        public virtual DbSet<RS_Roles> RS_Roles { get; set; }
        public virtual DbSet<RS_ServiceType> RS_ServiceType { get; set; }
        public virtual DbSet<RS_Site> RS_Site { get; set; }
        public virtual DbSet<RS_SiteInfo> RS_SiteInfo { get; set; }
        public virtual DbSet<RS_SiteSetting> RS_SiteSetting { get; set; }
        public virtual DbSet<RS_StatusType> RS_StatusType { get; set; }
        public virtual DbSet<RS_Transaction> RS_Transaction { get; set; }
        public virtual DbSet<RS_TransactionType> RS_TransactionType { get; set; }
        public virtual DbSet<RS_WebService> RS_WebService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
